### ISSUE TITLE
Missing helpfile on ADF

### ISSUE THREAD

**Issue by mankeli** [8bitbubsy/pt23f#3]
Pressing HELP key with the .adf says "Unable to open helpfile!"

**Comment by 8bitbubsy** [comment]
I can't reproduce this problem. I have tested with WinUAE using a cycle-accurate Amiga 500 configuration and auto-booting the ADF. Pressing HELP (Page Down on a PC keyboard) brings up the help screen just fine. It also works if I run the program from the floppy drive within Workbench, and even if the disk is in another drive than DF0.

Are you sure you got the correct ADF that is linked on the project's readme page? What kind of Amiga setup do you have?

**Comment by mankeli** [comment]
Yeah hmm, I guess I had the sample disk mounted when I tried it earlier today. Tested again and the help indeed opens okay. Kinda thought the whole tracker program was "single load" for some reason.. (I guess it could be with 512k slow memory expansion?)

Sorry for noise. :)
